<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="a_bot_base_scene" >

  <xacro:arg name="scene"		default=""/>
  <xacro:arg name="hw_interface"	default="PositionJointInterface"/>
					<!-- or "VelocityJointInterface" -->

  <xacro:property name="a_bot_x"	value="0"/>
  <xacro:property name="a_bot_y"	value="-0.4875"/>
  <xacro:property name="bots_z"		value="0.770"/>
  <xacro:property name="screen_z"	value="${bots_z + 0.0347}"/>

  <!-- ground -->
  <link name="ground"/>

  <!-- cage -->
  <xacro:property name="cage_w"		value="1.200"/>
  <xacro:property name="cage_l"		value="1.580"/>
  <xacro:property name="cage_h"		value="1.420"/>
  <xacro:property name="cage_t"		value="0.040"/>
  <xacro:property name="tool_bar_h"	value="0.240"/>
  <xacro:property name="camera_bar_h"	value="1.325"/>
  <xacro:property name="cage_z"		value="0.164"/>
  <xacro:property name="cage_offset_x"	value="0.015"/>
  <xacro:property name="cage_offset_y"	value="-0.005"/>
  <xacro:include filename="$(find aist_description
			   )/objects/urdf/cage.urdf.xacro"/>
  <xacro:cage prefix="cage_"
	      width="${cage_w}" length="${cage_l}" height="${cage_h}"
	      thickness="${cage_t}"
	      workspace_height="${bots_z - cage_z}"
	      tool_bar_height="${tool_bar_h}"
	      camera_bar_height="${camera_bar_h}"
	      parent="ground">
    <origin xyz="${-cage_w/2 + cage_offset_x}
		 ${-cage_l/2 + cage_offset_y}
		 ${cage_z}"
	    rpy="0 0 0" />
  </xacro:cage>

  <!-- workspace -->
  <xacro:property name="table_w"	value="0.900"/>
  <xacro:property name="table_l"	value="1.800"/>
  <xacro:include filename="$(find aist_description
			   )/objects/urdf/table.urdf.xacro"/>
  <xacro:table prefix="workspace_table_"
	       width="${table_w}" length="${table_l}" height="${bots_z}"
	       parent="ground">
    <origin xyz="${-cage_w/2 + cage_offset_x + cage_t} ${-table_l/2} 0"
	    rpy="0 0 0"/>
  </xacro:table>
  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- tool holders -->
  <xacro:property name="precision_tool_holder_y"	value="0.60"/>
  <xacro:property name="screw_tool_m3_holder_y"		value="0.70"/>
  <xacro:property name="screw_tool_m4_holder_y"		value="0.80"/>
  <xacro:property name="suction_tool_holder_y"		value="0.90"/>
  <xacro:include filename="$(find aist_description
			   )/objects/urdf/precision_tool_holder.urdf.xacro"/>
  <xacro:precision_tool_holder prefix="precision_tool_holder_"
			   parent="cage_tool_bar">
    <origin xyz="0 ${precision_tool_holder_y} ${cage_t}" rpy="0 0 0"/>
  </xacro:precision_tool_holder>
  <xacro:include filename="$(find aist_description
			   )/objects/urdf/screw_tool_holder.urdf.xacro"/>
  <xacro:screw_tool_holder prefix="screw_tool_m3_holder_"
			   parent="cage_tool_bar">
    <origin xyz="0 ${screw_tool_m3_holder_y} ${cage_t}" rpy="0 0 0"/>
  </xacro:screw_tool_holder>
  <xacro:screw_tool_holder prefix="screw_tool_m4_holder_"
			   parent="cage_tool_bar">
    <origin xyz="0 ${screw_tool_m4_holder_y} ${cage_t}" rpy="0 0 0"/>
  </xacro:screw_tool_holder>
  <xacro:include filename="$(find aist_description
			   )/objects/urdf/suction_tool_holder.urdf.xacro"/>
  <xacro:suction_tool_holder prefix="suction_tool_holder_"
			   parent="cage_tool_bar">
    <origin xyz="0 ${suction_tool_holder_y} ${cage_t}" rpy="0 0 0"/>
  </xacro:suction_tool_holder>

  <!-- robot arms -->
  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>
  <xacro:ur_robot_gazebo
      prefix="a_bot_"
      joint_limits_parameters_file="$(find ur_description
				    )/config/ur5e/joint_limits.yaml"
      physical_parameters_file="$(find ur_description
				)/config/ur5e/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description
			      )/config/ur5e/visual_parameters.yaml"
      kinematics_parameters_file="$(find aist_bringup
				  )/config/a_bot_calibration.yaml"
      transmission_hw_interface="hardware_interface/$(arg hw_interface)"
      safety_limits="true"
      safety_pos_margin="0.3"/>

  <joint name="ground_a_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="a_bot_base_link"/>
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- Attach mounter for Zivid2+ camera -->
  <!-- <xacro:include filename="$(find aist_description)/devices/urdf/zivid_coupling.urdf.xacro"/> -->
  <!-- <xacro:zivid_coupling prefix="a_bot_zivid_coupling_" parent="a_bot_flange"> -->
  <!--   <origin xyz="0 0 0" rpy="${pi} 0 0" /> -->
  <!-- </xacro:zivid_coupling> -->

  <!-- <!-\- Spawn and attach Zivid2+ camera -\-> -->
  <!-- <xacro:include filename="$(find aist_description -->
  <!-- 			   )/scenes/urdf/load_calibration.urdf.xacro"/> -->
  <!-- <xacro:load_calibration filename="$(find aist_handeye_calibration -->
  <!-- 				    )/calib/a_bot_zivid.yaml"/> -->
  <!-- <xacro:include filename="$(find aist_description -->
  <!-- 			   )/devices/urdf/zivid2plus.urdf.xacro"/> -->
  <!-- <xacro:zivid2plus name="a_bot_zivid" -->
  <!-- 		    parent="a_bot_zivid_coupling_flange_link"> -->
  <!--   <origin xyz="${origin[0]} ${origin[1]} ${origin[2]}" -->
  <!--   	    rpy="${origin[3]} ${origin[4]} ${origin[5]}"/> -->
  <!-- </xacro:zivid2plus> -->

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_arg2f_coupling.urdf.xacro"/>
  <xacro:robotiq_arg2f_coupling prefix="a_bot_gripper_coupling_"
				parent="a_bot_flange">
    <origin xyz="0 0 0" rpy="${pi} 0 0"/>
  </xacro:robotiq_arg2f_coupling>

  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_140_gripper.urdf.xacro"/>
  <xacro:robotiq_140_gripper prefix="a_bot_gripper_"
			     parent="a_bot_gripper_coupling_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_140_gripper>

  <!-- RealSense cameras -->
  <xacro:include filename="$(find aist_description
  			   )/devices/urdf/sr305_on_2f140.urdf.xacro" />
  <xacro:sr305_on_2f140 prefix="a_bot_"
  			parent="a_bot_gripper_base_link"
  			use_nominal_extrinsics="true"/>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:if value="${'$(arg scene)' != ''}">
    <xacro:include filename="$(find aist_description)/scenes/urdf/$(arg
			     scene).urdf.xacro"/>
  </xacro:if>

</robot>
