<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="a_bot__base_scene" >

  <xacro:arg name="scene" default=""/>

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="a_bot_x" value="0"/>
  <xacro:property name="a_bot_y" value="-0.4875"/>
  <!-- <xacro:property name="a_bot_theta" value="${pi}"/> -->

  <xacro:property name="bots_z" value="0.77"/>

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="ground"/>

  <xacro:include filename="$(find aist_description)/objects/urdf/aist_box.urdf.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="1.8"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:aist_box name="workbox"
		  width="${table_w}" length="${table_l}" height="${table_h}"
		  parent="ground">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:aist_box>
  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <!-- <xacro:include filename="$(find ur_description)/urdf/common.gazebo.xacro"/> -->
  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>
  <xacro:ur_robot_gazebo
      prefix="a_bot_"
      joint_limits_parameters_file="$(find ur_description
				    )/config/ur5/joint_limits.yaml"
      physical_parameters_file="$(find ur_description
				)/config/ur5/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description
			      )/config/ur5/visual_parameters.yaml"
      kinematics_parameters_file="$(find aist_bringup
				  )/config/a_bot_calibration.yaml"
      transmission_hw_interface="hardware_interface/PositionJointInterface"/>

  <joint name="ground_a_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="a_bot_base_link"/>
    <origin xyz="${a_bot_x} ${a_bot_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- Spawn and attach force sensor -->
  <xacro:include filename="$(find aist_robotiq)/urdf/ft300.urdf.xacro"/>
  <xacro:ft300 prefix="a_bot_ftsensor_" parent="a_bot_flange">
    <origin xyz="0 0 0" rpy="${pi} 0 0"/>
  </xacro:ft300>

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_arg2f_coupling.urdf.xacro"/>
  <xacro:robotiq_arg2f_coupling prefix="a_bot_gripper_coupling_"
				parent="a_bot_ftsensor_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_arg2f_coupling>

  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_85_gripper.urdf.xacro"/>
  <xacro:robotiq_85_gripper prefix="a_bot_gripper_"
			    parent="a_bot_gripper_coupling_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_85_gripper>

  <!-- Add RealSense camera -->
  <xacro:include filename="$(find aist_description
			   )/devices/urdf/wrist_cameras.urdf.xacro" />
  <xacro:wrist_cameras prefix="a_bot_"
		       parent="a_bot_gripper_base_link"
		       use_nominal_extrinsics="true"/>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:if value="${'$(arg scene)' != ''}">
    <xacro:include filename="$(find aist_description)/scenes/urdf/$(arg
			     scene).urdf.xacro"/>
  </xacro:if>

</robot>
