<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="fvision_base_scene" >

  <xacro:arg name="scene" default=""/>

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="d_bot_x" value="0"/>
  <xacro:property name="d_bot_y" value="0.4875"/>
  <xacro:property name="d_bot_theta" value="${pi}"/>

  <xacro:property name="bots_z" value="0.77"/>

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <!-- Main workspace -->
  <!-- The surface is 0.01 m below the robot bases and the "workspace_center" frame. -->
  <link name="ground"/>

  <xacro:include filename="$(find aist_description)/objects/urdf/aist_box.urdf.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="0.75"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:aist_box name="workbox"
		  width="${table_w}" length="${table_l}" height="${table_h}"
		  parent="ground">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:aist_box>
  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>
  <xacro:ur_robot_gazebo
      prefix="d_bot_"
      joint_limits_parameters_file="$(find ur_description
                                    )/config/ur5e/joint_limits.yaml"
      physical_parameters_file="$(find ur_description
                                )/config/ur5e/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description
                              )/config/ur5e/visual_parameters.yaml"
      kinematics_parameters_file="$(find aist_bringup
				  )/config/d_bot_calibration.yaml"
      transmission_hw_interface="hardware_interface/PositionJointInterface"/>

  <joint name="ground_d_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link= "d_bot_base_link"/>
    <origin xyz="${d_bot_x} ${d_bot_y} ${bots_z}" rpy="0 0 ${d_bot_theta}"/>
  </joint>

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_dual_bracket.urdf.xacro"/>
  <xacro:robotiq_dual_bracket prefix="d_bot_dual_bracket_"
			      parent="d_bot_flange">
    <origin xyz="0 0 0" rpy="${pi} 0 0"/>
  </xacro:robotiq_dual_bracket>

  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_arg2f_coupling.urdf.xacro"/>
  <xacro:robotiq_arg2f_coupling prefix="d_bot_left_coupling_"
				parent="d_bot_dual_bracket_left_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_arg2f_coupling>

  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_140_gripper.urdf.xacro"/>
  <xacro:robotiq_140_gripper prefix="d_bot_gripper_"
			     parent="d_bot_left_coupling_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_140_gripper>

  <xacro:robotiq_arg2f_coupling prefix="d_bot_right_coupling_"
				parent="d_bot_dual_bracket_right_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_arg2f_coupling>

  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_epick.urdf.xacro"/>
  <xacro:robotiq_epick prefix="d_bot_suction_"
		       parent="d_bot_right_coupling_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_epick>

  <!-- Add PhoXi 3D scanner -->
  <xacro:include filename="$(find
			   aist_phoxi_camera)/urdf/phoxi_m_camera.urdf.xacro"/>
  <xacro:phoxi_m_camera name="d_phoxi_m_camera" parent="workspace_center">
    <origin xyz="-0.0149511700982
		 -0.483543436025
		 0.633792706454"
	    rpy="${-152.286950706*pi/180}
		 ${-2.00315281361*pi/180}
		 ${0*pi/180}"/>
  </xacro:phoxi_m_camera>

  <!-- Add RealSense camera -->
  <xacro:include filename="$(find aist_description
			   )/devices/urdf/_sr305.urdf.xacro"/>
  <xacro:sensor_sr305 name="d_bot_camera" parent="d_bot_gripper_base_link">
    <origin xyz="0.030 0.000 0.043" rpy="0 ${0.0*pi/180.0} 0" />
  </xacro:sensor_sr305>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:if value="${'$(arg scene)' != ''}">
    <xacro:include filename="$(find aist_description)/scenes/urdf/$(arg
			     scene).urdf.xacro"/>
  </xacro:if>

</robot>
