<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="g_bot_base_scene" >

  <!-- This is the main file defining our robot arrangement and physical environment. -->

  <xacro:arg name="scene" default=""/>

  <xacro:property name="g_bot_x"   value="0"/>
  <xacro:property name="g_bot_y"   value="-0.920"/>
  <xacro:property name="g_bot_z"   value="0.700"/>
  <xacro:property name="cabinet_w" value="0.900"/>
  <xacro:property name="cabinet_l" value="0.400"/>
  <xacro:property name="cabinet_b" value="0.100"/>
  <xacro:property name="shelf1_h"  value="0.600"/>
  <xacro:property name="shelf2_h"  value="0.990"/>
  <xacro:property name="back_h"    value="1.500"/>
  <xacro:property name="mounter_w" value="0.200"/>
  <xacro:property name="mounter_l" value="0.200"/>

  <link name="ground"/>

  <!-- Main workspace -->
  <xacro:include filename="$(find aist_description
			   )/objects/urdf/cabinet.urdf.xacro"/>
  <xacro:cabinet prefix=""
		 width="${cabinet_w}" length="${cabinet_l}"
		 base_height="${cabinet_b}"
		 shelf1_height="${shelf1_h}"
		 shelf2_height="${shelf2_h}"
		 shelf3_height="${shelf3_h}"
		 back_height  ="${back_h}"
		 parent="ground">
    <origin xyz="${-cabinet_w/2} ${-cabinet_l/2} 0" rpy="0 0 0"/>
  </xacro:cabinet>

  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${shelf3_h}" rpy="0 0 0"/>
  </joint>

  <!-- Robot mounter -->
  <xacro:include filename="$(find aist_description
			   )/objects/urdf/table.urdf.xacro"/>
  <xacro:table prefix="mounter_"
		 width="${mounter_w}" length="${mounter_l}" height="${g_bot_z}"
		 parent="ground">
    <origin xyz="${g_bot_x - mounter_w/2} ${g_bot_y - mounter_l/2} 0"
	    rpy="0 0 0"/>
  </xacro:table>

  <!-- Robot arm -->
  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>
  <xacro:ur_robot_gazebo
      prefix="g_bot_"
      joint_limits_parameters_file="$(find ur_description
				    )/config/ur5e/joint_limits.yaml"
      physical_parameters_file="$(find ur_description
				)/config/ur5e/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description
			      )/config/ur5e/visual_parameters.yaml"
      kinematics_parameters_file="$(find aist_bringup
				  )/config/g_bot_calibration.yaml"
      transmission_hw_interface="hardware_interface/PositionJointInterface"/>

  <joint name="ground_g_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="g_bot_base_link"/>
    <origin xyz="${g_bot_x} ${g_bot_y} ${g_bot_z}" rpy="0 0 0"/>
  </joint>

  <!-- Attach gripper -->
  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_arg2f_coupling.urdf.xacro"/>
  <xacro:robotiq_arg2f_coupling prefix="g_bot_gripper_coupling_"
				parent="g_bot_flange">
    <origin xyz="0 0 0" rpy="${pi} 0 0"/>
  </xacro:robotiq_arg2f_coupling>

  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_140_gripper.urdf.xacro"/>
  <xacro:robotiq_140_gripper prefix="g_bot_gripper_"
			     parent="g_bot_gripper_coupling_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_140_gripper>

  <!-- Attach RealSense camera -->
  <xacro:include filename="$(find aist_description
			   )/scenes/urdf/load_calibration.urdf.xacro"/>
  <xacro:load_calibration filename="$(find aist_handeye_calibration
				    )/calib/g_bot_camera.yaml"/>
  <xacro:include filename="$(find aist_description
			   )/devices/urdf/_d435.urdf.xacro"/>
  <xacro:sensor_d435 name="g_bot_camera" parent="workspace_center"
		     use_nominal_extrinsics="true">
    <origin xyz="${origin[0]} ${origin[1]} ${origin[2]}"
    	    rpy="${origin[3]} ${origin[4]} ${origin[5]}"/>
  </xacro:sensor_d435>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:if value="${'$(arg scene)' != ''}">
    <xacro:include filename="$(find aist_description)/scenes/urdf/$(arg
			     scene).urdf.xacro"/>
  </xacro:if>

</robot>
