<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro" name="mocap_base_scene">

  <xacro:arg name="scene" default=""/>

  <!-- Calibration help: If the robot is not moving far enough to the calibration point, increase these distances -->
  <xacro:property name="c_bot_x" value="0"/>
  <xacro:property name="c_bot_y" value="-0.4875"/>

  <xacro:property name="bots_z" value="0.77"/>

  <!-- Main workspace -->
  <link name="ground"/>

  <xacro:include filename="$(find aist_description)/objects/urdf/aist_box.urdf.xacro"/>
  <xacro:property name="table_w" value="0.9"/>
  <xacro:property name="table_l" value="0.75"/>
  <xacro:property name="table_h" value="0.01"/>
  <xacro:aist_box name="workbox"
		  width="${table_w}" length="${table_l}" height="${table_h}"
		  parent="ground">
    <origin xyz="${-table_w/2} ${-table_l/2} ${bots_z - table_h}" rpy="0 0 0"/>
  </xacro:aist_box>
  <link name="workspace_center"/>
  <joint name="ground_to_workspace" type="fixed">
    <parent link="ground"/>
    <child  link="workspace_center"/>
    <origin xyz="0 0 ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- robot arms -->
  <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro"/>
  <xacro:ur_robot_gazebo
      prefix="c_bot_"
      joint_limits_parameters_file="$(find ur_description
                                    )/config/ur5e/joint_limits.yaml"
      physical_parameters_file="$(find ur_description
                                )/config/ur5e/physical_parameters.yaml"
      visual_parameters_file="$(find ur_description
                              )/config/ur5e/visual_parameters.yaml"
      kinematics_parameters_file="$(find aist_bringup
				  )/config/c_bot_calibration.yaml"
      transmission_hw_interface="hardware_interface/PositionJointInterface"/>

  <joint name="ground_c_bot_joint" type="fixed">
    <parent link="ground"/>
    <child  link="c_bot_base_link"/>
    <origin xyz="${c_bot_x} ${c_bot_y} ${bots_z}" rpy="0 0 0"/>
  </joint>

  <!-- Spawn and attach gripper -->
  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_arg2f_coupling.urdf.xacro"/>
  <xacro:robotiq_arg2f_coupling prefix="c_bot_gripper_coupling_"
				parent="c_bot_flange">
    <origin xyz="0 0 0" rpy="${pi} 0 0"/>
  </xacro:robotiq_arg2f_coupling>

  <xacro:include filename="$(find aist_robotiq
			   )/urdf/robotiq_85_gripper.urdf.xacro"/>
  <xacro:robotiq_85_gripper prefix="c_bot_gripper_"
			    parent="c_bot_gripper_coupling_flange_link">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:robotiq_85_gripper>

  <!-- Add RealSense camera -->
  <xacro:include filename="$(find aist_description
			   )/scenes/urdf/load_calibration.urdf.xacro"/>
  <xacro:load_calibration directory="$(find aist_handeye_calibration)/calib"
			  name="realsenseD435"/>
  <xacro:include filename="$(find aist_description
			   )/devices/urdf/_d435.urdf.xacro"/>
  <xacro:sensor_d435 name="realsenseD435" parent="workspace_center"
		     use_nominal_extrinsics="true">
    <origin xyz="${origin[0]} ${origin[1]} ${origin[2]}"
    	    rpy="${origin[3]} ${origin[4]} ${origin[5]}"/>
  </xacro:sensor_d435>

  <!-- I would like to remove the "world" link definition, but apparently it is necessary for Gazebo -->
  <link name="world"/>
  <joint name="world_ground_joint" type="fixed">
    <parent link="world"/>
    <child  link="ground"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Include indivisual scene file -->
  <xacro:if value="${'$(arg scene)' != ''}">
    <xacro:include filename="$(find aist_description)/scenes/urdf/$(arg
			     scene).urdf.xacro"/>
  </xacro:if>

</robot>
