screw_tool_m3:
  primitives:
  - type:       BOX                     # The bit cushion and motor
    dimensions: [.04, .026, .055]
    pose:       [-0.009, 0.0, 0.0275, 0.0, 0.0, 0.0]
  - type:       CYLINDER
    dimensions: [.08, .0085]
    pose:       [0.0, 0.0, -0.04, 0.0, 0.0, 0.0]
  - type:       CYLINDER                # The cylinder representing the tip
    dimensions: [0.018, 0.0035]
    pose:       [0.0, 0.0, -0.089, 0.0, 0.0, 0.0]
  visual_meshes:
  - url:        'package://aist_fastening_tools/meshes/visual/screw_tool_m3_BC5-XL320-R-AY2.6-EH2.stl'
    pose:       [0.0, 0.0, -0.0008, 0.0, 0.0, -90.0]
    scale:      [0.001, 0.001, 0.001]
    color:      [0.8, 0.8, 0.8, 1.0]
  collision_meshes:
  - url:        'package://aist_fastening_tools/meshes/collision/screw_tool_m3_simplified.stl'
    pose:       [0.0, 0.0, 0.0, 0.0, 0.0, -90.0]
    scale:      [0.0001, 0.0001, 0.0001]
  subframes:
    tip_link:   [0.0, 0.0, -0.1, 0.0, 0.0, 0.0]

screw_tool_m4:
  primitives:
  - type:       BOX                     # The bit cushion and motor
    dimensions: [0.04, 0.026, 0.055]
    pose:       [-0.009, 0.0, 0.0275, 0.0, 0.0, 0.0]
  - type:       CYLINDER                # The "shaft" + suction attachment
    dimensions: [0.08, .0085]
    pose:       [0.0, 0.0, -0.04, 0.0, 0.0, 0.0]
  - type:       CYLINDER                # The cylinder representing the tip
    dimensions: [.038, .0035]
    pose:       [0.0, 0.0, -0.099, 0.0, 0.0, 0.0]
  visual_meshes:
  - url:        'package://aist_fastening_tools/meshes/visual/screw_tool_m4_BC5-XL320-AY3.5-EH3R4.stl'
    pose:       [0.0, 0.0, -0.0008, 0.0, 0.0, -90.0]
    scale:      [0.001, 0.001, 0.001]
    color:      [0.8, 0.8, 0.8, 1.0]
  collision_meshes:
  - url:        'package://aist_fastening_tools/meshes/collision/screw_tool_m4_simplified.stl'
    pose:       [0.0, 0.0, 0.0, 0.0, 0.0, -90.0]
    scale:      [0.0001, 0.0001, 0.0001]
  subframes:
    tip_link:   [0.0, 0.0, -0.12, 0.0, 0.0, 0.0]

suction_tool:
  primitives:
  - type:       BOX                     # The bit cushion and motor
    dimensions: [0.032, 0.076, 0.046]
    pose:       [0.000, 0.000, 0.023, 0.0, 0.0, 0.0]
  - type:       CYLINDER                # The "shaft" + suction attachment
    dimensions: [0.105, 0.005]
    pose:       [0.0, -0.003, -0.0525, 0.0, 0.0, 0.0]
  visual_meshes:
  - url:        'package://aist_fastening_tools/meshes/visual/suction_tool.stl'
    pose:       [-0.035, -0.038, -0.105, 90.0, 0.0, 90.0]
    scale:      [0.001, 0.001, 0.001]
    color:      [0.8, 0.8, 0.8, 1.0]
  subframes:
    tip_link:   [0.0, -0.003, -0.105, 0.0, 0.0, 0.0]

base_fixture:
  primitives:
  - type:        BOX                     # Body
    dimensions:  [0.049, 0.058, 0.026]
    pose:        [-0.0245, 0.0, 0.013, 0.0, 0.0, 0.0]
  - type:        BOX                     # Piston
    dimensions:  [0.007, 0.056, 0.022]
    pose:        [0.0095, 0.0, 0.013, 0.0, 0.0, 0.0]
  visual_meshes:
  - url:         'package://aist_fastening_tools/meshes/visual/MGPM12-20Z_body.stl'
    pose:        [0.0, 0.0, 0.013, 0.0, 0.0, 180.0]
    scale:       [0.001, 0.001, 0.001]
    color:       [0.8, 0.8, 0.8, 1.0]
  - url:         'package://aist_fastening_tools/meshes/visual/MGPM12-20Z_piston.stl'
    pose:        [0.0, 0.0, 0.013, 0.0, 0.0, 180.0]
    scale:       [0.001, 0.001, 0.001]
    color:       [0.8, 0.8, 0.8, 1.0]
  subframes:
    tip_link:    [0.033, 0.0, 0.013, 0.0, 0.0, 0.0]
    piston_head: [0.013, 0.0, 0.013, 0.0, 0.0, 0.0]
