# screw tool controller stuffs
motor_id:              2  # ID of Dynamixel servo motor

# suction tool controller stuffs
digital_in_port:       0  # The pin to which the pressure sensor is connected
digital_out_port_suck: 0  # The pin to which the 'vac'  of pump is connected
digital_out_port_blow: 1  # The pin to which the 'blow' of pump is connected
