camera_type: DepthCamera
camera_name: a_bot_inside_camera
robot_name: a_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: a_bot_flange
robot_effector_tip_frame: a_bot_gripper_tip_link
camera_parent_frame: a_bot_gripper_base_link
marker_map: markermap-17-26-32-256
marker_size: 0.07
detection_mode: 1
planarity_tolerance: 0.003
initpose: [0.00, 0.05, 0.40, 90, 90, 0]
keyposes:
  - [-0.15,  0.05, 0.40, 90,  60,   0]
  - [-0.07,  0.05, 0.40, 90,  75,   0]
  - [-0.00,  0.05, 0.40, 90,  90,   0]
  - [ 0.07,  0.05, 0.40, 90, 105,   0]
  - [ 0.15,  0.05, 0.40, 90, 120,   0]
  - [-0.00,  0.20, 0.40,  0,  60, -90]
  - [-0.00,  0.15, 0.40,  0,  70, -90]
  - [-0.00,  0.10, 0.40,  0,  80, -90]
  - [-0.00,  0.00, 0.40,  0, 100, -90]
