camera_name: a_motioncam
robot_name: b_bot
eye_on_hand: false
robot_base_frame: workspace_center
robot_effector_frame: b_bot_gripper_base_link
robot_effector_tip_frame: b_bot_gripper_tip_link
camera_parent_frame: workspace_center
marker_map: aruco-26-70x70-5
enclosed_marker: false
detection_mode: 0
planarity_tolerance: 0.001
initpose: [0.10,  0.10, 0.35, 0, 90, 0]
keyposes:
  - [0.24,  0.12, 0.13, 30, 25, 0]
  - [0.24,  0.00, 0.13, 30, 25, 0]
  - [0.24, -0.12, 0.13, 30, 25, 0]

  - [0.00, -0.15, 0.14, 30, 25, 0]
  - [0.00,  0.00, 0.14, 30, 25, 0]
  - [0.00,  0.15, 0.14, 30, 25, 0]
