camera_name: a_motioncam
robot_name: b_bot
eye_on_hand: false
robot_base_frame: workspace_center
robot_effector_frame: b_bot_gripper_base_link
robot_effector_tip_frame: b_bot_gripper_tip_link
camera_parent_frame: workspace_center
marker_map: aruco-26-70x70-5
enclosed_marker: false
detection_mode: 1
planarity_tolerance: 0.001
initpose: [0.10,  0.10, 0.35, 0, 90, 0]
keyposes:
  - [0.16,  0.15, 0.15, 40, 25, 0]
  - [0.16,  0.03, 0.15, 30, 25, 0]
  - [0.16, -0.08, 0.15, 20, 25, 0]

  - [-0.05, -0.10, 0.23, 20, 25, 0]
  - [-0.05,  0.03, 0.23, 30, 25, 0]
  - [-0.05,  0.15, 0.23, 40, 25, 0]
