camera_type: DepthCamera
camera_name: f_bot_camera
robot_name: f_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: f_bot_flange
robot_effector_tip_frame: f_bot_gripper_tip_link
camera_parent_frame: f_bot_gripper_base_link
marker_map: markermap-17_26_32_256
enclosed_marker: true
detection_mode: 1
planarity_tolerance: 0.003
initpose: [0.00, -0.05, 0.40, 90, 90, 0]
keyposes:
  - [-0.22, -0.05, 0.40, 90,  60,   0]
  - [-0.12, -0.05, 0.40, 90,  75,   0]
  - [-0.02, -0.05, 0.40, 90,  90,   0]
  - [ 0.08, -0.05, 0.40, 90, 105,   0]
  - [ 0.18, -0.05, 0.40, 90, 120,   0]
  - [-0.02,  0.15, 0.40,  0,  60, -90]
  - [-0.02,  0.05, 0.40,  0,  75, -90]
  - [-0.02, -0.20, 0.40,  0, 105, -90]
  - [-0.02, -0.30, 0.40,  0, 120, -90]
