camera_name: realsenseD435
robot_name: c_bot
eye_on_hand: false
robot_base_frame: workspace_center
robot_effector_frame: c_bot_gripper_base_link
robot_effector_tip_frame: c_bot_gripper_tip_link
camera_parent_frame: workspace_center
marker_map: aruco-17_26_32_256-150x150-5
planarity_tolerance: 0.01
initpose: [0.00, 0.07, 0.50, -90, 90, 0]
keyposes:
  - [-0.20,  0.00, 0.30, -150, 150, -90]
  - [-0.20, -0.20, 0.35, -150, 150, -90]

  - [ 0.00, -0.20, 0.35, -150, 150, -90]
  - [ 0.00,  0.00, 0.30, -150, 150, -90]

  - [ 0.20,  0.00, 0.30, -150, 150, -90]
  - [ 0.20, -0.20, 0.35, -150, 150, -90]
