# Goal
string tool_name  # "m3_tool", "m4_tool",...
bool   tighten    # True: tighten, False: loosen
bool   retighten  # True:  after tightening fully, the motor loosens
                  #        the screw for one second and then tightens again.
                  #        This can protect against some failures.
                  # False: skips the retightening, good for the idler pulley.
uint32 speed      # 0 to 1023
---
# Result
bool   stalled    # True: the motor stopped before the timeout
---
# Feedback
int32  speed
int16  current
