# Goal
bool tighten     # True: tighten, False: loosen
bool retighten   # True:  after tightening fully, the motor loosens
                 #        the screw for one second and then tightens again.
                 #        This can protect against some failures.
                 # False: skips the retightening, good for the idler pulley.
uint32 speed     # 0 to 1023
---
# Result
bool stalled     # True: the motor stopped before the timeout
---
# Feedback
float64 speed    # ratio to the maximum speed   (-1.0 <= speed   <= 1.0)
float64 current  # ratio to the maximum current (-1.0 <= current <= 1.0)
