controller_list:
  - name: fake_b_bot_controller
    type: $(arg fake_execution_type)
    joints:
      - b_bot_shoulder_pan_joint
      - b_bot_shoulder_lift_joint
      - b_bot_elbow_joint
      - b_bot_wrist_1_joint
      - b_bot_wrist_2_joint
      - b_bot_wrist_3_joint
initial:  # Define initial robot poses per group
  - group: b_bot
    pose: home