camera_type: DepthCamera
camera_name: d_bot_camera
robot_name: d_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: d_bot_ee_link
camera_frame: calibrated_d_bot_camera_color_optical_frame
marker_id: 26
marker_size: 0.07
planarity_tolerance: 0.003
initpose: [0.00, 0.05, 0.35, 90, 90, 0]
keyposes:
  - [-0.13,  0.10, 0.35, 90,  60,   0]
  - [-0.08,  0.10, 0.35, 90,  75,   0]
  - [ 0.00,  0.10, 0.35, 90,  90,   0]
  - [ 0.08,  0.10, 0.35, 90, 105,   0]
  - [ 0.13,  0.10, 0.35, 90, 120,   0]
  - [ 0.00, -0.10, 0.35,  0, 120, -90]
  - [ 0.00,  0.05, 0.35,  0, 110, -90]
  - [ 0.00,  0.15, 0.35,  0,  80, -90]
  - [ 0.00,  0.20, 0.35,  0,  75, -90]

camera_body_frame: d_bot_camera_link
camera_optical_frame: d_bot_camera_color_optical_frame
