<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="object" params="name prefix parent properties_file
				     *origin">

    <!-- local macros -->
    <xacro:macro name="load_properties" params="filename">
      <xacro:property name="properties"
		      value="${xacro.load_yaml(filename)[name]}"/>
      <xacro:property name="visual_meshes"
		      value="${properties['visual_meshes']}"
		      scope="parent"/>
      <xacro:property name="primitives"
		      value="${properties.get('primitives', list())}"
		      scope="parent"/>
      <xacro:property name="subframes"
		      value="${properties.get('subframes', dict())}"
		      scope="parent"/>
      <xacro:property name="grasp_points"
		      value="${properties.get('grasp_points', dict())}"
		      scope="parent"/>
    </xacro:macro>

    <xacro:macro name="set_subframes" params="subframes">
      <xacro:if value="${len(subframes)}">
	<xacro:property name="subframe"	value="${subframes.popitem()}"/>
	<joint name="${prefix}${subframe[0]}_joint" type="fixed">
	  <parent link="${prefix}base_link"/>
	  <child  link="${prefix}${subframe[0]}"/>
	  <origin xyz="${subframe[1][0]} ${subframe[1][1]} ${subframe[1][2]}"
		  rpy="${radians(subframe[1][3])}
		       ${radians(subframe[1][4])}
		       ${radians(subframe[1][5])}"/>
	</joint>
	<link name="${prefix}${subframe[0]}"/>

	<xacro:set_subframes subframes="${subframes}"/>
      </xacro:if>
    </xacro:macro>

    <xacro:macro name="set_mesh" params="mesh id">
      <xacro:property name="pose"	value="${mesh['pose']}"/>
      <xacro:property name="scale"	value="${mesh['scale']}"/>
      <xacro:property name="color"	value="${mesh['color']}"/>

      <origin xyz="${pose[0]} ${pose[1]} ${pose[2]}"
    	      rpy="${radians(pose[3])}
		   ${radians(pose[4])}
		   ${radians(pose[5])}"/>
      <geometry>
        <mesh filename="${mesh['url']}"
    	      scale="${scale[0]} ${scale[1]} ${scale[2]}"/>
      </geometry>
      <material name="${name}/color_${id}">
	<color rgba="${color[0]} ${color[1]} ${color[2]} ${color[3]}"/>
      </material>
    </xacro:macro>

    <xacro:macro name="set_meshes" params="meshes collision">
      <xacro:if value="${len(meshes)}">
	<xacro:if value="${collision}">
	  <collision>
	    <xacro:set_mesh mesh="${meshes[0]}" id="${len(meshes) - 1}"/>
	  </collision>
	</xacro:if>
	<xacro:if value="${not collision}">
	  <visual>
	    <xacro:set_mesh mesh="${meshes[0]}" id="${len(meshes) - 1}"/>
	  </visual>
	</xacro:if>

	<xacro:set_meshes meshes="${meshes[1:]}" collision="${collision}"/>
      </xacro:if>
    </xacro:macro>

    <xacro:macro name="set_primitive" params="primitive">
      <xacro:property name="type"	value="${primitive['type']}"/>
      <xacro:property name="pose"	value="${primitive['pose']}"/>
      <xacro:property name="dims"	value="${primitive['dimensions']}"/>

      <origin xyz="${pose[0]} ${pose[1]} ${pose[2]}"
	      rpy="${radians(pose[3])}
		   ${radians(pose[4])}
		   ${radians(pose[5])}"/>
      <geometry>
	<xacro:if value="${type == 'BOX'}">
	  <box size="${dims[0]} ${dims[1]} ${dims[2]}"/>
	</xacro:if>
	<xacro:if value="${type == 'CYLINDER'}">
	  <cylinder length="${dims[0]}" radius="${dims[1]}"/>
	</xacro:if>
	<xacro:if value="${type == 'SPHERE'}">
	  <sphere radius="${dims[0]}"/>
	</xacro:if>
      </geometry>
    </xacro:macro>

    <xacro:macro name="set_primitives" params="primitives collision">
      <xacro:if value="${len(primitives)}">
	<xacro:if value="${collision}">
	  <collision>
	    <xacro:set_primitive primitive="${primitives[0]}"/>
	  </collision>
	</xacro:if>
	<xacro:if value="${not collision}">
	  <visual>
	    <xacro:set_primitive primitive="${primitives[0]}"/>
	  </visual>
	</xacro:if>

	<xacro:set_primitives primitives="${primitives[1:]}"
			      collision="${collision}"/>
      </xacro:if>
    </xacro:macro>

    <!-- load object properties -->
    <xacro:load_properties filename="${properties_file}"/>

    <!-- a joint from myself to parent -->
    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${parent}"/>
      <child  link="${prefix}base_link"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <!-- my link -->
    <link name="${prefix}base_link">
      <xacro:set_meshes meshes="${visual_meshes}" collision="False"/>
      <xacro:set_primitives primitives="${primitives}" collision="True"/>
    </link>

    <!-- subframes and grasp points -->
    <xacro:set_subframes subframes="${subframes}"/>
    <xacro:set_subframes subframes="${grasp_points}"/>

  </xacro:macro>
</robot>
