#
# - If 'object_type' is emtpy, attach the existing collision object
#   with 'object_id' to the 'target_link' at the 'pose'. Current target
#   link before attaching new one is returned in 'retval'.
# - If 'object_type' is not empty, a new object with 'object_id'
#   of 'object_type' will be created and then attached.
# -
uint8 ATTACH_OBJECT=1
#
# - Append 'touch_links' to the existing touch links of the object
#   with 'object_id'.
#
uint8 APPEND_TOUCH_LINKS=2
#
# - Remove 'touch_links' from the existing touch links of the object
#   with 'object_id'.
#
uint8 REMOVE_TOUCH_LINKS=3
#
# - Delete the collision object with 'object_id'.
# - If 'object_id' is empty, all collision objects attached to 'target_link'
#   will be deleted.
# - If 'target_link' is also empty, all collision objects in the scene
#   will be deleted.
#
uint8 REMOVE_OBJECT=5
#
# - Return the object type of the existing collision object with 'object_id'
#   in 'retval'.
#
uint8 GET_OBJECT_TYPE=6

uint8              op
string             object_type
string             object_id
string             target_link
string             source_subframe
geometry_msgs/Pose pose
string[]           touch_links
---
bool               success
string             retval