controller_list:
  - name: /d_bot/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - d_bot_shoulder_pan_joint
      - d_bot_shoulder_lift_joint
      - d_bot_elbow_joint
      - d_bot_wrist_1_joint
      - d_bot_wrist_2_joint
      - d_bot_wrist_3_joint
  - name: d_bot_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - d_bot_gripper_finger_joint