camera_type: DepthCamera
camera_name: realsenseD435
robot_name: c_bot
eye_on_hand: false
robot_base_frame: workspace_center
robot_effector_frame: c_bot_flange
robot_effector_tip_frame: c_bot_gripper_tip_link
marker_id: 32
marker_size: 0.16
planarity_tolerance: 0.01
initpose: [0.00, 0.07, 0.50, -90, 90, 0]
keyposes:
  - [-0.10,  0.15, 0.30, 30, 30, 90]
  - [-0.10,  0.10, 0.15, 30, 30, 90]

  - [0.05,   0.0, 0.05, 30, 30, 90]
  - [0.00,  0.10, 0.30, 30, 30, 90]

  - [0.10,  0.15, 0.15, 30, 30, 90]
  - [0.10,  0.00, 0.30, 30, 30, 90]

body_frame: realsenseD435_link
tcp_frame: realsenseD435_color_optical_frame
