#################################
# PID parameters for pose seeking
#################################

# Input low-pass filter
input_low_pass_filter_half_order: 3
input_low_pass_filter_cutoff_frequency: 20.0

# Maximum value of error integral for all PID controllers
windup_limit: 5.0

# PID gains
x_proportional_gain: 250.0
y_proportional_gain: 250.0
z_proportional_gain: 250.0
x_integral_gain: 1.4 #10.0
y_integral_gain: 1.4 #10.0
z_integral_gain: 1.4 #10.0
x_derivative_gain: 0.0 #5.0
y_derivative_gain: 0.0 #5.0
z_derivative_gain: 0.0 #5.0

angular_proportional_gain: 40.0 #100.0
angular_integral_gain: 0.5 #5.0
angular_derivative_gain: 0.0 #2.5
