<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!--
  Author: Cristian Beltran
-->

  <xacro:macro name="precision_gripper" params="prefix parent *origin">

    <xacro:include filename="$(find aist_precision_gripper
			     )/urdf/precision_transmission.xacro"/>
    <xacro:precision_transmission prefix="${prefix}"/>

    <xacro:property name="horizontal_offset"		value="-0.015"/>
    <xacro:property name="tip_distance"			value="0.147"/>
    <xacro:property name="rail_distance"		value="0.0915"/>
    <xacro:property name="max_gap"			value="0.010"/>
    <xacro:property name="depth"			value="0.030"/>
    <xacro:property name="motor_width"			value="0.045"/>
    <xacro:property name="motor_height"			value="0.0425"/>
    <xacro:property name="lower_body_width"		value="0.085"/>
    <xacro:property name="lower_body_height"		value="0.050"/>
    <xacro:property name="finger_collision_width"	value="0.003"/>

    <!-- base -->
    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${parent}"/>
      <child  link="${prefix}base_link"/>
      <xacro:insert_block name="origin"/>
    </joint>
    <link name="${prefix}base_link">
      <visual>
	<origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
          <mesh filename="package://aist_precision_gripper/meshes/precision_body.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gazebo/Black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="${motor_height/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${motor_height} ${motor_width} ${depth}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.86387"/>
        <inertia ixx="1017560E-9" ixy="0" ixz="2235E-9"
		 iyy="1028041E-9" iyz="0" izz="489810E-9"/>
      </inertial>
    </link>

    <!-- lower body(collision only) -->
    <joint name="${prefix}lower_body_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child  link="${prefix}lower_body_link"/>
      <origin xyz="${motor_height} ${horizontal_offset} 0" rpy="0 0 0"/>
    </joint>
    <link name="${prefix}lower_body_link">
      <collision>
	<origin xyz="${lower_body_height/2} 0 0" rpy="0 0 0"/>
	<geometry>
	  <box size="${lower_body_height} ${lower_body_width} ${depth}"/>
	</geometry>
      </collision>
    </link>

    <!-- left finger -->
    <joint name="${prefix}finger_joint" type="prismatic">
      <origin xyz="${rail_distance} ${horizontal_offset} 0" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_finger"/>
      <axis xyz="0 1 0"/>
      <limit effort="130" lower="0" upper="${max_gap/2}" velocity="0.15"/>
    </joint>
    <link name="${prefix}left_finger">
      <visual>
	<origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
          <mesh filename="package://aist_precision_gripper/meshes/precision_left_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gazebo/Grey">
          <color rgba="0.7 0.7 0.7 1"/>
        </material>
      </visual>
      <collision>
	<origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
	<geometry>
          <mesh filename="package://aist_precision_gripper/meshes/collision/precision_left_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
	<!-- <origin xyz="${(tip_distance - rail_distance)/2} -->
	<!-- 	     ${finger_collision_width/2} 0" -->
	<!-- 	rpy="0 0 0"/> -->
	<!-- <geometry> -->
	<!--   <box size="${tip_distance - rail_distance} -->
	<!-- 	     ${finger_collision_width} -->
	<!-- 	     ${finger_collision_width}"/> -->
	<!-- </geometry> -->
      </collision>
      <inertial>
        <origin xyz="0.02262 -0.00759 0.00738" rpy="0 0 0"/>
        <mass value="0.03804"/>
        <inertia ixx="13567E-9" ixy="1849E-9" ixz="3622E-9"
		 iyy="15784E-9" iyz="3616E-9" izz="7478E-9"/>
      </inertial>
    </link>

    <!-- right finger -->
    <joint name="${prefix}right_finger_joint" type="prismatic">
      <origin xyz="${rail_distance} ${horizontal_offset} 0" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_finger"/>
      <axis xyz="0 -1 0"/>
      <limit effort="130" lower="0" upper="${max_gap/2}" velocity="0.15"/>
      <mimic joint="${prefix}finger_joint" multiplier="1" offset="0"/>
    </joint>
    <link name="${prefix}right_finger">
      <visual>
	<origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
        <geometry>
          <mesh filename="package://aist_precision_gripper/meshes/precision_right_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gazebo/Grey">
          <color rgba="0.7 0.7 0.7 1"/>
        </material>
      </visual>
      <colliaion>
	<origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
	<geometry>
          <mesh filename="package://aist_precision_gripper/meshes/collision/precision_right_finger.stl" scale="0.001 0.001 0.001"/>
        </geometry>
	<!-- <origin xyz="${(tip_distance - rail_distance)/2} -->
	<!-- 	     ${-finger_collision_width/2} 0" -->
	<!-- 	rpy="0 0 0"/> -->
	<!-- <geometry> -->
	<!--   <box size="${tip_distance - rail_distance} -->
	<!-- 	     ${finger_collision_width} -->
	<!-- 	     ${finger_collision_width}"/> -->
	<!-- </geometry> -->
      </colliaion>
      <inertial>
        <origin xyz="-0.02262 0.00759 0.00738" rpy="0 0 0"/>
        <mass value="0.03804"/>
        <inertia ixx="13567E-9" ixy="1849E-9" ixz="-3622E-9"
		 iyy="15784E-9" iyz="-3616E-9" izz="7478E-9"/>
      </inertial>
    </link>

    <joint name="${prefix}tip_link_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child  link="${prefix}tip_link"/>
      <origin xyz="${tip_distance} ${horizontal_offset} 0" rpy="0 ${-pi/2} 0"/>
    </joint>
    <link name="${prefix}tip_link"/>

    <gazebo reference="${prefix}base_link">
      <material>Gazebo/FlatBlack</material>
    </gazebo>
    <gazebo reference="${prefix}left_finger">
      <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="${prefix}right_finger">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Improve grasping physics -->
    <gazebo reference="${prefix}left_finger">
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <minDepth>0.001</minDepth>
    </gazebo>
    <gazebo reference="${prefix}right_finger">
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <minDepth>0.001</minDepth>
    </gazebo>

    <!-- Mimic joints -->
    <gazebo>
      <plugin filename="libgazebo_mimic_joint_plugin.so"
	      name="${prefix}mimic_precision">
        <joint>${prefix}finger_joint</joint>
        <mimicJoint>${prefix}right_finger_joint</mimicJoint>
        <multiplier>1.0</multiplier>
        <offset>0.0</offset>
      </plugin>
    </gazebo>

  </xacro:macro>
</robot>
