<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="precision_gripper" params="prefix parent *origin">

    <xacro:macro name="load_properties" params="filename">
      <xacro:property name="properties"
		      value="${xacro.load_yaml(filename)['precision_gripper']}"/>
      <xacro:property name="visual_meshes"
		      value="${properties['visual_meshes']}"
		      scope="parent"/>
      <xacro:property name="collision_meshes"
		      value="${properties['collision_meshes']}"
		      scope="parent"/>
      <xacro:property name="subframes"
		      value="${properties['subframes']}"
		      scope="parent"/>
    </xacro:macro>

    <xacro:include filename="$(find aist_precision_gripper
			     )/urdf/precision_transmission.xacro"/>
    <xacro:precision_transmission prefix="${prefix}"/>
    <xacro:load_properties filename="$(find aist_precision_gripper
				     )/config/precision_gripper_properties.yaml"/>

    <xacro:property name="max_gap"	value="0.010"/>

    <!-- base -->
    <xacro:property name="base_vorigin"	value="${visual_meshes[0]['pose']}"/>
    <xacro:property name="base_vscale"	value="${visual_meshes[0]['scale']}"/>
    <xacro:property name="base_vcolor"	value="${visual_meshes[0]['color']}"/>
    <xacro:property name="base_corigin"
		    value="${collision_meshes[0]['pose']}"/>
    <xacro:property name="base_cscale"
		    value="${collision_meshes[0]['scale']}"/>

    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${parent}"/>
      <child  link="${prefix}base_link"/>
      <xacro:insert_block name="origin"/>
    </joint>
    <link name="${prefix}base_link">
      <visual>
	<origin xyz="${base_vorigin[0]}
		     ${base_vorigin[1]}
		     ${base_vorigin[2]}"
		rpy="${base_vorigin[3]*pi/180.0}
		     ${base_vorigin[4]*pi/180.0}
		     ${base_vorigin[5]*pi/180.0}"/>
        <geometry>
          <mesh filename="${visual_meshes[0]['url']}"
		scale="${base_vscale[0]} ${base_vscale[1]} ${base_vscale[2]}"/>
        </geometry>
        <material name="Gazebo/Black">
          <color rgba="${base_vcolor[0]} ${base_vcolor[1]}
		       ${base_vcolor[2]} ${base_vcolor[3]}"/>
        </material>
      </visual>
      <collision>
	<origin xyz="${base_corigin[0]}
		     ${base_corigin[1]}
		     ${base_corigin[2]}"
		rpy="${base_corigin[3]*pi/180.0}
		     ${base_corigin[4]*pi/180.0}
		     ${base_corigin[5]*pi/180.0}"/>
        <geometry>
          <mesh filename="${collision_meshes[0]['url']}"
		scale="${base_cscale[0]} ${base_cscale[1]} ${base_cscale[2]}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.86387"/>
        <inertia ixx="1017560E-9" ixy="0" ixz="2235E-9"
		 iyy="1028041E-9" iyz="0" izz="489810E-9"/>
      </inertial>
    </link>

    <!-- left finger -->
    <xacro:property name="left_finger_vorigin"
		    value="${visual_meshes[1]['pose']}"/>
    <xacro:property name="left_finger_vscale"
		    value="${visual_meshes[1]['scale']}"/>
    <xacro:property name="left_finger_vcolor"
		    value="${visual_meshes[1]['color']}"/>
    <xacro:property name="left_finger_corigin"
		    value="${collision_meshes[1]['pose']}"/>
    <xacro:property name="left_finger_cscale"
		    value="${collision_meshes[1]['scale']}"/>

    <joint name="${prefix}finger_joint" type="prismatic">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}left_finger"/>
      <axis xyz="0 1 0"/>
      <limit effort="130" lower="0" upper="${max_gap/2}" velocity="0.15"/>
    </joint>
    <link name="${prefix}left_finger">
      <visual>
	<origin xyz="${left_finger_vorigin[0]}
		     ${left_finger_vorigin[1]}
		     ${left_finger_vorigin[2]}"
		rpy="${left_finger_vorigin[3]*pi/180.0}
		     ${left_finger_vorigin[4]*pi/180.0}
		     ${left_finger_vorigin[5]*pi/180.0}"/>
        <geometry>
          <mesh filename="${visual_meshes[1]['url']}"
		scale="${left_finger_vscale[0]}
		       ${left_finger_vscale[1]}
		       ${left_finger_vscale[2]}"/>
        </geometry>
        <material name="Gazebo/Grey">
          <color rgba="${left_finger_vcolor[0]} ${left_finger_vcolor[1]}
		       ${left_finger_vcolor[2]} ${left_finger_vcolor[3]}"/>
        </material>
      </visual>
      <collision>
	<origin xyz="${left_finger_corigin[0]}
		     ${left_finger_corigin[1]}
		     ${left_finger_corigin[2]}"
		rpy="${left_finger_corigin[3]*pi/180.0}
		     ${left_finger_corigin[4]*pi/180.0}
		     ${left_finger_corigin[5]*pi/180.0}"/>
        <geometry>
          <mesh filename="${collision_meshes[1]['url']}"
		scale="${left_finger_cscale[0]}
		       ${left_finger_cscale[1]}
		       ${left_finger_cscale[2]}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0.02262 -0.00759 0.00738" rpy="0 0 0"/>
        <mass value="0.03804"/>
        <inertia ixx="13567E-9" ixy="1849E-9" ixz="3622E-9"
		 iyy="15784E-9" iyz="3616E-9" izz="7478E-9"/>
      </inertial>
    </link>

    <!-- right finger -->
    <xacro:property name="right_finger_vorigin"
		    value="${visual_meshes[1]['pose']}"/>
    <xacro:property name="right_finger_vscale"
		    value="${visual_meshes[1]['scale']}"/>
    <xacro:property name="right_finger_vcolor"
		    value="${visual_meshes[1]['color']}"/>
    <xacro:property name="right_finger_corigin"
		    value="${collision_meshes[1]['pose']}"/>
    <xacro:property name="right_finger_cscale"
		    value="${collision_meshes[1]['scale']}"/>

    <joint name="${prefix}right_finger_joint" type="prismatic">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}right_finger"/>
      <axis xyz="0 -1 0"/>
      <limit effort="130" lower="0" upper="${max_gap/2}" velocity="0.15"/>
      <mimic joint="${prefix}finger_joint" multiplier="1" offset="0"/>
    </joint>
    <link name="${prefix}right_finger">
      <visual>
	<origin xyz="${right_finger_vorigin[0]}
		     ${right_finger_vorigin[1]}
		     ${right_finger_vorigin[2]}"
		rpy="${right_finger_vorigin[3]*pi/180.0}
		     ${right_finger_vorigin[4]*pi/180.0}
		     ${right_finger_vorigin[5]*pi/180.0}"/>
        <geometry>
          <mesh filename="${visual_meshes[2]['url']}"
		scale="${right_finger_vscale[0]}
		       ${right_finger_vscale[1]}
		       ${right_finger_vscale[2]}"/>
        </geometry>
        <material name="Gazebo/Grey">
          <color rgba="${right_finger_vcolor[0]} ${right_finger_vcolor[1]}
		       ${right_finger_vcolor[2]} ${right_finger_vcolor[3]}"/>
        </material>
      </visual>
      <collision>
	<origin xyz="${right_finger_corigin[0]}
		     ${right_finger_corigin[1]}
		     ${right_finger_corigin[2]}"
		rpy="${right_finger_corigin[3]*pi/180.0}
		     ${right_finger_corigin[4]*pi/180.0}
		     ${right_finger_corigin[5]*pi/180.0}"/>
        <geometry>
          <mesh filename="${collision_meshes[2]['url']}"
		scale="${right_finger_cscale[0]}
		       ${right_finger_cscale[1]}
		       ${right_finger_cscale[2]}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="-0.02262 0.00759 0.00738" rpy="0 0 0"/>
        <mass value="0.03804"/>
        <inertia ixx="13567E-9" ixy="1849E-9" ixz="-3622E-9"
		 iyy="15784E-9" iyz="-3616E-9" izz="7478E-9"/>
      </inertial>
    </link>

    <!-- tip -->
    <xacro:property name="tip_link_origin"
		    value="${subframes['tip_link']}"/>
    <joint name="${prefix}tip_link_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child  link="${prefix}tip_link"/>
      <origin xyz="${tip_link_origin[0]}
		   ${tip_link_origin[1]}
		   ${tip_link_origin[2]}"
	      rpy="${tip_link_origin[3]*pi/180.0}
		   ${tip_link_origin[4]*pi/180.0}
		   ${tip_link_origin[5]*pi/180.0}"/>
    </joint>
    <link name="${prefix}tip_link"/>

    <gazebo reference="${prefix}base_link">
      <material>Gazebo/FlatBlack</material>
    </gazebo>
    <gazebo reference="${prefix}left_finger">
      <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="${prefix}right_finger">
      <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Improve grasping physics -->
    <gazebo reference="${prefix}left_finger">
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <minDepth>0.001</minDepth>
    </gazebo>
    <gazebo reference="${prefix}right_finger">
      <kp>1000000.0</kp>
      <kd>1.0</kd>
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <minDepth>0.001</minDepth>
    </gazebo>

    <!-- Mimic joints -->
    <gazebo>
      <plugin filename="libgazebo_mimic_joint_plugin.so"
	      name="${prefix}mimic_precision">
        <joint>${prefix}finger_joint</joint>
        <mimicJoint>${prefix}right_finger_joint</mimicJoint>
        <multiplier>1.0</multiplier>
        <offset>0.0</offset>
      </plugin>
    </gazebo>

  </xacro:macro>
</robot>
