# This file contains metadata about the assembly.
description: A configuration of the WRS2020 assembly with the motor and bearing switched. 
            The bearing L-plate is rotated 180 degrees. The motor shaft is at the bottom.

panel_bearing_facing_backward: True
panel_motor_facing_backward: False
switched_motor_and_bearing: True

motor_shaft_down: True
