robots:
  a_bot:
    default_gripper: a_bot_gripper

grippers:
  a_bot_gripper:
    type:          RobotiqGripper
    controller_ns: a_bot_gripper_controller

cameras:
  a_bot_inside_camera:  CodedLightRealSenseCamera
  a_bot_outside_camera: CodedLightRealSenseCamera
