robots:
  a_bot:
    default_gripper: a_bot_gripper

grippers:
  a_bot_gripper:
    type:          RobotiqGripper
    controller_ns: a_bot_gripper_controller
  precision_tool:
    type:          PrecisionGripper
    controller_ns: precision_tool_controller
    base_link:     precision_tool/base_link
    tip_link:      precision_tool/tip_link
  screw_tool_m3:
    type:          SuctionGripper
    controller_ns: screw_tool_m3_controller
    base_link:     screw_tool_m3/base_link
    tip_link:      screw_tool_m3/tip_link
  screw_tool_m4:
    type:          SuctionGripper
    controller_ns: screw_tool_m4_controller
    base_link:     screw_tool_m4/base_link
    tip_link:      screw_tool_m4/tip_link
  base_fixture:
    type:          SuctionGripper
    controller_ns: base_fixture_controller

cameras:
  a_motioncam:          PhoXiCamera
#  a_bot_zivid:          ZividCamera
  a_bot_inside_camera:  CodedLightRealSenseCamera
  a_bot_outside_camera: CodedLightRealSenseCamera

fastening_tools:
  screw_tool_m3:
    type:          ScrewTool
    controller_ns: screw_tool_m3_fastening_controller
  screw_tool_m4:
    type:          ScrewTool
    controller_ns: screw_tool_m4_fastening_controller

moveit_eef_step: 0.002
