id: LTR-066
rate: 20.0
frame: a_motioncam_sensor
color_camera_frame: a_motioncam_color_camera_frame
send_point_cloud: true
send_normal_map: true
send_depth_map: true
send_confidence_map: false
send_event_map: false
send_texture: true
send_color_camera_image: true
operation_mode: 1
laser_power: 4095
led_power: 4095
camera_texture_source: 5
trigger_mode: 1
normals_estimation_radius: 1
white_balance: "Daylight (5000 - 6500K)"
maximum_fps: 20
camera_exposure: 10.24
scanner_exposure: 10.24
confidence: 3
exposure: 10.24
gamma: 1
intensity_scale: 0.5