robots:
  a_bot:
    default_gripper: a_bot_gripper
  b_bot:
    default_gripper: b_bot_gripper

grippers:
  a_bot_gripper:
    type: RobotiqGripper
    args:
      prefix: a_bot_gripper_
      effort: 5.0
      velocity: 0.1
#  a_bot_precision:
#    type: PrecisionGripper
#    args:
#      prefix: a_bot_precision_
  b_bot_gripper:
    type: SuctionGripper
    args:
      name: b_bot_gripper
      action_ns: /b_bot/suction_controller/suction
      state_ns: /b_bot/suction_tool/suctioned
      eject: false

cameras:
  a_phoxi_m_camera: PhoXiCamera
#  a_bot_inside_camera: RealSenseCamera
#  a_bot_outside_camera: RealSenseCamera
