robots:
  a_bot:
    default_gripper: a_bot_gripper
  b_bot:
    default_gripper: b_bot_gripper

grippers:
  a_bot_gripper:
    type:          RobotiqGripper
    controller_ns: a_bot_gripper_controller
    max_effort:    5.0
    velocity:      0.1
#  a_bot_precision:
#    type: PrecisionGripper
#    controller_ns: a_bot_gripper_controller
  b_bot_gripper:
    type:          SuctionGripper
    controller_ns: suction_tool_controller
cameras:
  a_phoxi_m_camera:     PhoXiCamera
  a_bot_inside_camera:  CodedLightRealSenseCamera
  a_bot_outside_camera: CodedLightRealSenseCamera

moveit_eef_step: 0.002