picking_parameters:
  precision_tool:
    approach_offset:  [0.000, 0.000,  0.050, 0.0, 0.0, 0.0]
    grasp_offset:     [0.000, 0.000, -0.030, 0.0, 0.0, 0.0]
    place_offset:     [0.000, 0.000, -0.029, 0.0, 0.0, 0.0]
    departure_offset: [0.000, 0.000,  0.050, 0.0, 0.0, 0.0]
    speed_fast:       1.0
    speed_slow:       0.1
    gripper_parameters:
      grasp_position:   0.000
      release_position: 0.065
      max_effort:       5.0
  screw_tool_m3:
    approach_offset:  [ 0.050, 0.000, 0.012, 0.0, 30.0, 0.0]
    grasp_offset:     [-0.005, 0.000, 0.010, 0.0, 30.0, 0.0]
    place_offset:     [-0.005, 0.000, 0.011, 0.0, 30.0, 0.0]
    departure_offset: [ 0.050, 0.000, 0.012, 0.0, 30.0, 0.0]
    speed_fast:       1.0
    speed_slow:       0.1
    gripper_parameters:
      grasp_position:   0.000
      release_position: 0.035
      max_effort:       5.0
  screw_tool_m4:
    approach_offset:  [ 0.050, 0.000, 0.012, 0.0, 30.0, 0.0]
    grasp_offset:     [-0.005, 0.000, 0.010, 0.0, 30.0, 0.0]
    place_offset:     [-0.005, 0.000, 0.011, 0.0, 30.0, 0.0]
    departure_offset: [ 0.050, 0.000, 0.012, 0.0, 30.0, 0.0]
    speed_fast:       1.0
    speed_slow:       0.1
    gripper_parameters:
      grasp_position:   0.000
      release_position: 0.035
      max_effort:       5.0
  suction_tool:
    approach_offset:  [ 0.050, 0.000, 0.012, 0.0, 30.0, 0.0]
    grasp_offset:     [-0.005, 0.000, 0.010, 0.0, 30.0, 0.0]
    place_offset:     [-0.005, 0.000, 0.011, 0.0, 30.0, 0.0]
    departure_offset: [ 0.050, 0.000, 0.012, 0.0, 30.0, 0.0]
    speed_fast:       1.0
    speed_slow:       0.1
    gripper_parameters:
      grasp_position:   0.000
      release_position: 0.035
      max_effort:       5.0

touch_links:
  a_bot_gripper_tip_link:
    - a_bot_gripper_left_inner_knucle
    - a_bot_gripper_left_inner_finger
    - a_bot_gripper_left_inner_finger_pad
    - a_bot_gripper_right_inner_knucle
    - a_bot_gripper_right_inner_finger
    - a_bot_gripper_right_inner_finger_pad
  precision_tool/tip_link:
    - precision_tool/left_finter
    - precision_tool/right_finter
  screw_tool_m3/tip_link:
    - screw_tool_m3/base_link
  screw_tool_m4/tip_link:
    - screw_tool_m4/base_link
  suction_tool_m4/tip_link:
    - suction_tool/base_link
  precision_tool_holder_link:
    - precision_tool_holder_base_link
  screw_tool_m3_holder_link:
    - screw_tool_m3_holder_base_link
  screw_tool_m4_holder_link:
    - screw_tool_m4_holder_base_link
