robots:
  b_bot:
    default_gripper: b_bot_gripper

grippers:
  b_bot_gripper:
    type:          SuctionGripper
    controller_ns: b_bot_gripper_controller
  precision_tool:
    type:          PrecisionGripper
    controller_ns: precision_tool_controller
    base_link:     precision_tool/base_link
    tip_link:      precision_tool/tip_link
  screw_tool_m3:
    type:          SuctionGripper
    controller_ns: screw_tool_m3_controller
    base_link:     screw_tool_m3/base_link
    tip_link:      screw_tool_m3/tip_link
  screw_tool_m4:
    type:          SuctionGripper
    controller_ns: screw_tool_m4_controller
    base_link:     screw_tool_m4/base_link
    tip_link:      screw_tool_m4/tip_link
  base_fixture:
    type:          SuctionGripper
    controller_ns: base_fixture_controller

cameras:
  a_phoxi_m_camera:     PhoXiCamera

moveit_eef_step: 0.002
