robots:
  a_khi:
    default_gripper: a_khi_gripper
  b_khi:
    default_gripper: b_khi_gripper

grippers:
  a_khi_gripper:
    type: RobotiqGripper
    args:
      prefix: a_khi_gripper_
      effort: 5.0
      velocity: 0.1
  b_khi_gripper:
    type: SuctionGripper
    args:
      name: b_khi_gripper
      action_ns: /b_khi/suction_controller/suction
      state_ns: /b_khi/suction_tool/suctioned
      eject: false
