robots:
  a_khi:
    default_gripper: magnet_gripper

grippers:
  magnet_gripper:
    type: SuctionGripper
    args:
      prefix: a_khi_magnet_
      base_link: a_khi_magnet_base_link
      tip_link: a_khi_magnet_link
      eject: false
  a_khi_gripper:
    type: Lecp6Gripper
    args:
      prefix: a_khi_

cameras:
  a_khi_camera: PhoXiCamera
