robots:
  c_bot:
    default_gripper: c_bot_gripper

grippers:
  c_bot_gripper:
    type:          RobotiqGripper
    controller_ns: c_bot_gripper_controller
    max_effort:    5.0
    velocity:      0.1

cameras:
  realsenseD435: DepthCamera
