robots:
  e_bot:
    default_gripper: e_bot_gripper

grippers:
  e_bot_gripper:
    type:          RobotiqGripper
    controller_ns: e_bot_gripper_controller
    max_effort:    5.0
    velocity:      0.1
