nep_ip: 163.220.51.108
rate:   10.0
ros_to_nep:
  - from: /tf
    to:   Kitting/transforms
  - from: /mesh_generator/mesh
    to:   Kitting/screen_mesh
  - from: /live_camera/image_raw
    to:   Kitting/image
  - from: /help
    to:   Kitting/request_help
  - from: /collision_marker
    to:   Kitting/collision_marker

nep_to_ros:
  - from: Kitting/pointing
    to:   /pointing
    type: aist_msgs/Pointing

services:
  - name:     /robot_description_provider/get_links
    request:  Kitting/get_links
    response: Kitting/links
  - name:     /object_database_server/get_mesh_resource
    request:  Kitting/get_mesh_resource
    response: Kitting/mesh_resource
