nep_ip: 163.220.51.108
rate:   10.0
ros_to_nep:
  - from: /joint_states
    to:   Kitting/joint_states
  - from: /urdf_publisher/transforms
    to:   Kitting/transforms
  - from: /mesh_generator/mesh
    to:   Kitting/screen_mesh
  - from: /live_camera/image_raw
    to:   Kitting/image
  - from: /help
    to:   Kitting/request_help

nep_to_ros:
  - from: Kitting/pointing
    to:   /pointing
    type: finger_pointing_msgs/pointing

services:
  - name:     /urdf_publisher/get_links
    request:  Kitting/get_links
    response: Kitting/links
    