robots:
  a_khi:
    default_gripper: a_khi_magnet

grippers:
  a_khi_magnet:
    type: SuctionGripper
    args:
      prefix: a_khi_magnet_
      tip_link: a_khi_magnet_link
      eject: false
  a_khi_gripper:
    type: Lecp6Gripper
    args:
      prefix: a_khi_

cameras:
  a_khi_camera: PhoXiCamera
