robots:
  a_khi:
    default_gripper: a_khi_gripper

grippers:
  a_khi_gripper:
    type: SuctionGripper
    args:
      name: a_khi_gripper
      action_ns: /a_khi/suction_controller/suction
      state_ns: /a_khi/suction_tool/suctioned
      eject: false
