robots:
  arm:
    default_gripper: magnet

grippers:
  magnet:
    type: MagswitchGripper
    args:
      prefix: magnet_
  gripper:
    type: Lecp6Gripper
    args:
      prefix: gripper_

cameras:
  camera: PhoXiCamera

moveit_pose_reference_frame: base_link
moveit_eef_step: 0.05
