controller_list:
  - name: fake_f_bot_controller
    type: $(arg fake_execution_type)
    joints:
      - f_bot_shoulder_pan_joint
      - f_bot_shoulder_lift_joint
      - f_bot_elbow_joint
      - f_bot_wrist_1_joint
      - f_bot_wrist_2_joint
      - f_bot_wrist_3_joint
  - name: fake_f_bot_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - f_bot_gripper_finger_joint
initial:  # Define initial robot poses.
  - group: f_bot
    pose: home
  - group: f_bot_gripper
    pose: grasp