# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: f_bot
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - f_bot_shoulder_pan_joint
    - f_bot_shoulder_lift_joint
    - f_bot_elbow_joint
    - f_bot_wrist_1_joint
    - f_bot_wrist_2_joint
    - f_bot_wrist_3_joint
    - f_bot_gripper_finger_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /f_bot/scaled_pos_joint_traj_controller
#  - name: /f_bot/scaled_vel_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - f_bot_shoulder_pan_joint
      - f_bot_shoulder_lift_joint
      - f_bot_elbow_joint
      - f_bot_wrist_1_joint
      - f_bot_wrist_2_joint
      - f_bot_wrist_3_joint
  - name: f_bot_gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: True
    joints:
      - f_bot_gripper_finger_joint
