controller_list:
  - name: /f_bot/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - f_bot_shoulder_pan_joint
      - f_bot_shoulder_lift_joint
      - f_bot_elbow_joint
      - f_bot_wrist_1_joint
      - f_bot_wrist_2_joint
      - f_bot_wrist_3_joint
  - name: f_bot_gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - f_bot_gripper_finger_joint