precision_tool:
  ID:                   1
  Return_Delay_Time:    0
  Operating_Mode:       5  # Current-based Position Control Mode
  Torque_Enable:        1
  Profile_Acceleration: 0
  Profile_Velocity:     0
