serial_port:  $(arg serial_port)
publish_rate: $(arg publish_rate)
joint_name:   $(arg prefix)finger_joint

min_position: 0.000
max_position: 0.010

min_velocity: 0.000
max_velocity: 0.010

min_effort:   0.0
max_effort:   1.0

open_motor_position:  2050
close_motor_position: 2300

speed_limit:           3

moving_motor_current: 7
grasping_motor_current: 13
