ID: 1

stall_timeout: 1.0

min_position: 0.000
max_position: 0.010

max_effort: 0.5

min_position_count: 2300
max_position_count: 2050

min_effort_count: 7
max_effort_count: 13

# Touch links (allow collision)
touch_links:
  - $(arg prefix)left_finger
  - $(arg prefix)right_finger
  - $(arg prefix)tip_link
