<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="robotiq_epick" params="prefix parent
					    plunger_radius:=0
					    plunger_length:=0
					    *origin">

    <xacro:property name="epick_length" value="0.101"/>
    <xacro:property name="epick_offset" value="-0.006"/>

    <link name="${prefix}base_link">
      <inertial>
        <origin xyz="0 0 0.0515" rpy="0 0 0" />
        <mass value="0.706" />
        <inertia ixx="3.084E-03" ixy="0" ixz="0"
		 iyy="2.999E-03" iyz="0" izz="0.546E-03"/>
      </inertial>
      <visual>
        <origin xyz="${epick_length + epick_offset} 0 0" rpy="0 0 ${-pi/2}" />
        <geometry>
          <mesh filename="package://aist_robotiq/meshes/visual/robotiq_epick.stl"
	  	scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="">
          <color rgba="0.1 0.1 0.1 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="${epick_length + epick_offset} 0 0" rpy="0 0 ${-pi/2}" />
        <geometry>
          <mesh filename="package://aist_robotiq/meshes/collision/robotiq_epick.stl"
		scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}base_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <!-- Add the force sensor in front of the gripper. -->
    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${parent}"/>
      <child  link="${prefix}base_link"/>
      <xacro:insert_block name="origin"/>
    </joint>

    <link name="${prefix}flange_link"/>
    <joint name="${prefix}flange_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child  link="${prefix}flange_link"/>
      <origin xyz="${epick_length} 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:if value="${plunger_length > 0}">
      <link name="${prefix}plunger_link">
	<inertial>
    	  <origin xyz="0 0 0" rpy="0 0 0"/>
    	  <mass value="0.100"/>
    	  <inertia ixx="0.0045" ixy="0" ixz="0"
		   iyy="0.0045"  iyz="0" izz="0.005"/>
	</inertial>
	<visual>
    	  <origin xyz="${plunger_length/2} 0 0" rpy="0 ${pi/2} 0"/>
    	  <geometry>
	    <cylinder radius="${plunger_radius}" length="${plunger_length}"/>
    	  </geometry>
          <material name="Grey">
            <color rgba="0.7 0.7 0.7 1.0"/>
          </material>
	</visual>
	<collision>
    	  <origin xyz="${plunger_length/2} 0 0" rpy="0 ${pi/2} 0"/>
    	  <geometry>
	    <cylinder radius="${plunger_radius}" length="${plunger_length}"/>
    	  </geometry>
	</collision>
      </link>
      <joint name="${prefix}plunger_joint" type="fixed">
	<parent link="${prefix}flange_link"/>
	<child  link="${prefix}plunger_link"/>
	<origin xyz="0 0 0" rpy="0 0 0"/>
      </joint>

      <link name="${prefix}tip_link"/>
      <joint name="${prefix}tip_joint" type="fixed">
	<parent link="${prefix}plunger_link"/>
	<child  link="${prefix}tip_link"/>
	<origin xyz="${plunger_length} 0 0" rpy="0 ${-pi/2} 0"/>
      </joint>

    </xacro:if>

  </xacro:macro>
</robot>
