collision_primitives:
- type: CYLINDER
  dimensions: [0.006, 0.0015]
  pose: [0.0, 0.0, 0.0, 0.0, pi/2, 0.0]
subframes:
- pose_xyzrpy:
  - 0.01
  - 0.0
  - 0.0
  - -pi/2
  - 0.0
  - 0.0
  name: screw_tip
- pose_xyzrpy:
  - 0.0
  - 0.0
  - 0.0
  - -pi/2
  - 0.0
  - 0.0
  name: screw_inserted
- pose_xyzrpy:
  - -0.003
  - 0.0
  - 0.0
  - -pi/2
  - 0.0
  - 0.0
  name: screw_head
grasp_points: []
