collision_primitives:
- type: CYLINDER
  dimensions: [0.005, 0.00575]
  pose: [0.0, 0.0, 0.0, 0.0, pi/2, 0.0]
subframes:
- pose_xyzrpy:
  - 0.0
  - 0.0
  - 0.0
  - -pi/2
  - 0.0
  - 0.0
  name: center
grasp_points: []
