camera_name: a_bot_camera
robot_name: a_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: a_bot_gripper_base_link
robot_effector_tip_frame: a_bot_gripper_tip_link
camera_parent_frame: a_bot_gripper_base_link
marker_map: aruco-17_26_32_256-150x150-5
enclosed_marker: true
detection_mode: 1
planarity_tolerance: 0.003
initpose: [0.00, 0.05, 0.40, -90, 90, 0]
keyposes:
  - [-0.19,  0.06, 0.40,  -90,  60,   0]
  - [-0.09,  0.06, 0.40,  -90,  75,   0]
  - [ 0.01,  0.06, 0.40,  -90,  90,   0]
  - [ 0.11,  0.06, 0.40,  -90, 105,   0]
  - [ 0.21,  0.06, 0.40,  -90, 120,   0]
  - [ 0.01,  0.17, 0.40, -180,  75, -90]
  - [ 0.01,  0.03, 0.40, -180,  90, -90]
  - [ 0.01, -0.10, 0.40, -180, 110, -90]
  - [ 0.01, -0.20, 0.40, -180, 125, -90]
