camera_name: b_bot_camera
robot_name: b_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: b_bot_gripper_base_link
robot_effector_tip_frame: b_bot_gripper_tip_link
camera_parent_frame: b_bot_gripper_base_link
marker_map: aruco-17_26_32_256-150x150-5
enclosed_marker: true
detection_mode: 1
planarity_tolerance: 0.003
initpose: [0.00, 0.05, 0.40, 90, 90, 0]
keyposes:
  - [-0.19, -0.04, 0.30,  90,  60,   0]
  - [-0.09, -0.04, 0.30,  90,  75,   0]
  - [ 0.02, -0.04, 0.30,  90,  90,   0]
  - [ 0.11, -0.04, 0.30,  90, 105,   0]
  - [ 0.21, -0.04, 0.30,  90, 120,   0]
  - [ 0.02,  0.05, 0.30,   0,  75, -90]
  - [ 0.02, -0.02, 0.30,   0,  90, -90]
  - [ 0.02, -0.16, 0.30,   0, 110, -90]
  - [ 0.02, -0.23, 0.30,   0, 125, -90]
