camera_name: d_bot_camera
robot_name: d_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: d_bot_gripper_base_link
robot_effector_tip_frame: d_bot_gripper_tip_link
camera_parent_frame: d_bot_gripper_base_link
marker_map: aruco-100_101_102_103-150x150-5
planarity_tolerance: 0.003
initpose: [0.00, 0.05, 0.30, 90, 90, 0]
keyposes:
  - [-0.18,  0.05, 0.35, 90,  60, 0]
  - [-0.13,  0.05, 0.35, 90,  70, 0]
  - [-0.05,  0.05, 0.35, 90,  80, 0]
  - [ 0.03,  0.05, 0.35, 90,  90, 0]
  - [ 0.08,  0.05, 0.35, 90, 100, 0]
  - [ 0.00,  0.20, 0.35,  0,  60, -90]
  - [ 0.00,  0.10, 0.35,  0,  75, -90]
  - [ 0.00, -0.05, 0.35,  0, 105, -90]
  - [ 0.00, -0.10, 0.35,  0, 120, -90]
