arms:
  b_bot:
    type:            URe
    default_gripper: b_bot_gripper
    active_controllers:
      - joint_trajectory_controller
      - motion_control_handle
    consistent_controllers:
      - joint_state_broadcaster
    real_consistent_controllers:
      - force_torque_sensor_broadcaster
      - io_and_status_controller
      - speed_scaling_state_broadcaster
      - tcp_pose_broadcaster
      - ur_configuration_controller
    inactive_controllers:
      - forward_velocity_controller
      - forward_effort_controller
      - forward_position_controller
      - cartesian_compliance_controller
      - cartesian_force_controller
      - cartesian_motion_controller
    real_inactive_controllers:
      - force_mode_controller
      - passthrough_trajectory_controller
      - freedrive_mode_controller
      - tool_contact_controller

grippers:
  b_bot_grippers:
    type: RobotiqDevices
    grippers:
      b_bot_gripper:
        type: RobotiqGripper
  precision_tools:
    type: DynamixelDevices
    grippers:
      precision_tool:
        type: PrecisionTool
  screw_tools:
    type: DynamixelDevices
    grippers:
      screw_tool_m3:
        type: ScrewTool
      screw_tool_m4:
        type: ScrewTool
  suction_tools:
    type: URioDevices
    grippers:
      suction_tool:
        type: SuctionTool
      base_fixture:
        type: SuctionGripper

cameras:
  a_motioncam:
    type: PhoXiCamera
  b_bot_camera:
    type: CodedLightRealsenseCamera
  live_camera:
    type: USBCamera
