joint_state_controller:
  type:         joint_state_controller/JointStateController
  publish_rate: &loop_hz $(arg frequency)

$(arg prefix)controller:
  type: position_controllers/JointTrajectoryController
  action_ns: follow_joint_trajectory  # for moveit
  action_type: FollowJointTrajectory  # for moveit (==>type)
  action_default: true                # for moveit (==>default)
  joints: &robot_joints
    - $(arg prefix)joint1
    - $(arg prefix)joint2
    - $(arg prefix)joint3
    - $(arg prefix)joint4
    - $(arg prefix)joint5
    - $(arg prefix)joint6
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.1
    $(arg prefix)joint1: {trajectory: 0, goal: 0.2}
    $(arg prefix)joint2: {trajectory: 0, goal: 0.2}
    $(arg prefix)joint3: {trajectory: 0, goal: 0.2}
    $(arg prefix)joint4: {trajectory: 0, goal: 0.2}
  state_publish_rate:  *loop_hz
  action_monitor_rate: 20
  #hold_trajectory_duration: 0

$(arg prefix)joint_group_controller:
  type: position_controllers/JointGroupPositionController
  joints: *robot_joints
