# Goal
string    camera_name
string    robot_name
string    end_effector_link
bool      eye_on_hand
float64[] initpose
float64[] keyposes
---
# Result
string    stage
bool      success
---
# Feedback
string    stage