<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="screw_feeder">

  <xacro:macro name="screw_feeder"
	       params="prefix parent with_collision_geometry:=true *origin">
  <!-- This creates a screw feeder (roughly) with the origin in the back right corner. -->
  <!-- This is the feeder: https://www.monotaro.com/g/02001466/ -->

  <xacro:property name="height" value=".147" />
  <xacro:property name="width"  value=".126" />
  <xacro:property name="length" value=".182" />

  <link name="${prefix}base_link">
    <inertial>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="1.0" ixy="0" ixz="0" iyy="1.0" iyz="0" izz="1.0"/>
    </inertial>
    <!-- Back side -->
    <visual>
      <origin xyz="${(length-.05)/2} ${width/2} ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${length-.05} ${width} ${height}"/>
      </geometry>
      <material name="black">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    <xacro:if value="${with_collision_geometry}">
      <collision>
        <origin xyz="${(length-.05)/2} ${width/2} ${height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${length-.05} ${width} ${height}"/>
        </geometry>
      </collision>
    </xacro:if>
    <!-- Front side -->
    <visual>
      <origin rpy="0 0 0" xyz="${(length-.025)} ${width/2} ${height/4}"/>
      <geometry>
        <box size="${.05} ${width} ${height/2}"/>
      </geometry>
      <material name="black">
        <color rgba=".2 .2 .2 1"/>
      </material>
    </visual>
    <xacro:if value="${with_collision_geometry}">
      <collision>
        <origin xyz="${(length-.025)} ${width/2} ${height/4}" rpy="0 0 0"/>
        <geometry>
          <box size="${.05} ${width} ${height/2}"/>
        </geometry>
      </collision>
    </xacro:if>

    <!-- The screw output area -->
    <visual>
      <origin xyz="${(length-.025)} ${width/2} ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${.05} ${.02} ${.005}"/>
      </geometry>
      <material name="gray">
        <color rgba=".6 .6 .6 1"/>
      </material>
    </visual>
    <xacro:if value="${with_collision_geometry}">
      <collision>
        <origin xyz="${(length-.025)} ${width/2} ${height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${.05} ${.02} ${.005}"/>
        </geometry>
      </collision>
    </xacro:if>
  </link>

  <joint name="${prefix}base_joint" type="fixed">
    <parent link="${parent}" />
    <child link ="${prefix}base_link" />
    <xacro:insert_block name="origin"/>
  </joint>

  <joint name="${prefix}outlet_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}outlet_link"/>
    <origin xyz="${length-.01} ${width/2} ${height/2}" rpy="0 0 0"/>
  </joint>
  <link name="${prefix}outlet_link"/>

  <joint name="${prefix}inlet_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}inlet_link"/>
    <origin xyz="${length/3} ${width/3} ${height}" rpy="0 0 0"/>
  </joint>
  <link name="${prefix}inlet_link"/>
  </xacro:macro>
</robot>
