controller_list:
  - name: fake_e_bot_controller
    type: $(arg execution_type)
    joints:
      - e_bot_shoulder_pan_joint
      - e_bot_shoulder_lift_joint
      - e_bot_elbow_joint
      - e_bot_wrist_1_joint
      - e_bot_wrist_2_joint
      - e_bot_wrist_3_joint
  - name: fake_e_bot_gripper_controller
    type: $(arg execution_type)
    joints:
      - e_bot_gripper_finger_joint
initial:  # Define initial robot poses.
  - group: e_bot
    pose: home
  - group: e_bot_gripper
    pose: close