screw_3:
  id: 'screw_tool_m3'
  frame_id: 'screw_tool_m3_base_link'
  primitives:
    [
      { # The bit cushion and motor
        type: 'BOX',
        dimensions: [.026, .04, .055],
        pose: [0.0, -0.009, 0.0275, 0.0, 0.0, 0.0]
      },
      { # The "shaft" + suction attachment
        type: 'BOX',
        dimensions: [.019, .03, .08],
        pose: [0.0, -0.0055, -0.04, 0.0, 0.0, 0.0]
      },
      { # The cylinder representing the tip
        type: 'CYLINDER',
        dimensions: [.018, .0035],
        pose: [0.0, 0.0, -0.089, 0.0, 0.0, 0.0]
      },
    ]
  subframe:
    name: 'screw_tool_m3_tip_link'
    pose: [0.0, 0.0, -0.1, 0.0, 0.0, 0.0]
  mesh_url: 'package://aist_fastening_tools/meshes/visual/screw_tool_m3_BC5-XL320-R-AY2.6-EH2.stl'

screw_4:
  id: 'screw_tool_m4'
  frame_id: 'screw_tool_m4_base_link'
  primitives:
    [
      { # The bit cushion and motor
        type: 'BOX',
        dimensions: [.026, .04, .055],
        pose: [0.0, -0.009, 0.0275, 0.0, 0.0, 0.0]
      },
      { # The "shaft" + suction attachment
        type: 'BOX',
        dimensions: [.019, .03, .08],
        pose: [0.0, -0.0055, -0.04, 0.0, 0.0, 0.0]
      },
      { # The cylinder representing the tip
        type: 'CYLINDER',
        dimensions: [.038, .0035],
        pose: [0.0, 0.0, -0.099, 0.0, 0.0, 0.0]
      },
    ]
  subframe:
    name: 'screw_tool_m4_tip_link'
    pose: [0.0, 0.0, -0.12, 0.0, 0.0, 0.0]
  mesh_url: 'package://aist_fastening_tools/meshes/visual/screw_tool_m4_BC5-XL320-AY3.5-EH3R4.stl'
